### PR TITLE
Pip 20.3.3

### LINKED ISSUE #3: Doesn't handle > 3 columns bed files
Bed files with more than 3 columns are not handled because of this line:
```
Traceback (most recent call last):
  File "/usr/bin/region_coverage.py", line 120, in <module>
    (region_chrom, region_start, region_end, region_region_id) = entry.split("\t")
ValueError: too many values to unpack
```

Suggested fix: `entry.split("\t")[0:4]`

### LINKED ISSUE #9: pysam install fails
`pip install pysam==0.7.6` now fails, so the app fails

`pip2 install pysam==0.7.6` seems to work, but would need testing within the app

### PR DESCRIPTION
**Pull request by sophie22**
Recent release of pip 21 no longer supports Python 2.7 which this app is written in, so the app broke. It is now fixed by specifying pip to upgrade to 20.3.3 version (which worked previously and during testing).
Minor changes to resolve issues on GitHub, now closed: #3 , #4 , #6, #9

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @sophie22)

___
*[src/dnanexus_region_coverage.sh, line 25 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT08TWl1GXNThTJiCW1:-MT08TWm5XdEwudI-36M:b9ikahp) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L25)):*
> ```Shell
>     echo "Value of bam_index: '$bam_index'"
>     echo "Value of input_bed: '$input_bed'"
>     echo "Value of input_bed: '$suffix'"
> ```

these aren't really needed, if you do it needs to say `value of bed_suffix`
___
*[src/dnanexus_region_coverage.sh, line 33 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT0AOPw5_0iiHZrk6_E:-MT0AOPw5_0iiHZrk6_F:b82bknd) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L33)):*
> ```Shell
>     # recover the original filenames, you can use the output of "dx describe
>     # "$variable" --name".
> ```

the suffix could have been parsed from the bed file with something like:

```
suffix=$(echo $input_bed | sed -e 's/.bed//')
suffix=$(echo $suffix | sed -e 's/refseq_//')
```

this will strip `.bed` from the end and `refseq_` from the beginning, so will pass any different bed files without having to specify it as an input

@mattgarner do you agree with this?
___
*[src/dnanexus_region_coverage.sh, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT08eSi-3jKXgxFxvbW:-MT08eSi-3jKXgxFxvbX:b-hkd9pq) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L43)):*
> ```Shell
>     echo "installing dependencies"
> 
>     pip install --upgrade pip==20.3.3
> ```

this could have been a local package of pip the same as for pysam, then it would be fully local and not require external dependency: `pip install pip-20.2.2.tar.gz`
___
*[src/dnanexus_region_coverage.sh, line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT095SMBgEoWBLMPlyE:-MT095SMBgEoWBLMPlyF:b4jqcwi) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L44)):*
> ```Shell
> 
>     pip install --upgrade pip==20.3.3
>     pip install pysam-0.7.6.tar.gz #pysam==0.7.6
> ```

unneeded comment
___
*[src/dnanexus_region_coverage.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT09Gm1D7kN17qTuNsA:-MT09Gm1D7kN17qTuNsB:b7wee6e) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L48)):*
> ```Shell
>     echo "running coverage calculations"
> 
>     #mkdir -p coverage_stats
> ```

remove commented lines

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @sophie22)

___
*[src/dnanexus_region_coverage.sh, line 25 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT08TWl1GXNThTJiCW1:-MT0JZAx2gAOmagK4HcZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L25)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

these aren't really needed, if you do it needs to say `value of bed_suffix`
</blockquote></details>

Done.
___
*[src/dnanexus_region_coverage.sh, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT08eSi-3jKXgxFxvbW:-MT0MXRAC_9NTszWkLPg:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L43)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this could have been a local package of pip the same as for pysam, then it would be fully local and not require external dependency: `pip install pip-20.2.2.tar.gz`
</blockquote></details>

Done.
___
*[src/dnanexus_region_coverage.sh, line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT095SMBgEoWBLMPlyE:-MT0JnEV576_SXFGH9RY:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L44)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

unneeded comment
</blockquote></details>

Done.
___
*[src/dnanexus_region_coverage.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT09Gm1D7kN17qTuNsA:-MT0JoTs2pcxxBGTkkWd:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L48)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

remove commented lines
</blockquote></details>

Done.

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[src/dnanexus_region_coverage.sh, line 33 at r1](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT0AOPw5_0iiHZrk6_E:-MT11T-A-z1fs7S4xneg:b-79l97f) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/f7c4149457a815ee28338e6fcb3b7da2e2cb9dbd/src/dnanexus_region_coverage.sh#L33)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

the suffix could have been parsed from the bed file with something like:

```
suffix=$(echo $input_bed | sed -e 's/.bed//')
suffix=$(echo $suffix | sed -e 's/refseq_//')
```

this will strip `.bed` from the end and `refseq_` from the beginning, so will pass any different bed files without having to specify it as an input

@mattgarner do you agree with this?
</blockquote></details>

he says it's a nice improvement but not essential as the app will be retired fairly soon

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[src/dnanexus_region_coverage.sh, line 46 at r3](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT139p7-U0cLY0ukAoh:-MT139p82zN6C3vLJom2:b1v6zco) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/380f8e336d8132cd9eb6e3e5ed4b935fbd6e1e80/src/dnanexus_region_coverage.sh#L46)):*
> ```Shell
> 
>     echo "running coverage calculations"
>     bed_suffix=$(echo $input_bed | sed -e 's/.bed//')
> ```

either use this or the optional string input, as this will overwrite the input if provided. If you've done testing with the optional input just stick with that

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[src/dnanexus_region_coverage.sh, line 46 at r3](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10#-MT139p7-U0cLY0ukAoh:-MT1IxSc2FhTHinmuTCU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_region_coverage/blob/380f8e336d8132cd9eb6e3e5ed4b935fbd6e1e80/src/dnanexus_region_coverage.sh#L46)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

either use this or the optional string input, as this will overwrite the input if provided. If you've done testing with the optional input just stick with that
</blockquote></details>

Done.

**Comment by sophie22** [comment]
Job finishes without errors, output is named correctly
https://platform.dnanexus.com/projects/Fq37P984PFX505413bg4779f/monitor/job/G0QbgBj4PFXK2y7p71KQ8QJv

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_region_coverage/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
